// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odefgakegyypdioshdmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZWZnYWtlZ3l5cGRpb3NoZG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTY0NjUsImV4cCI6MjA2Mzc3MjQ2NX0.rOJOgsLUdSg68MDQO3641Pp2PEETvrNZ1BRGtwWsn4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);